[2023-12-11T21:31:15.181+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_hook_overview.upload_to_snowflake manual__2023-12-11T21:31:10.670571+00:00 [queued]>
[2023-12-11T21:31:15.186+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_hook_overview.upload_to_snowflake manual__2023-12-11T21:31:10.670571+00:00 [queued]>
[2023-12-11T21:31:15.186+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-11T21:31:15.191+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_snowflake> on 2023-12-11 21:31:10.670571+00:00
[2023-12-11T21:31:15.195+0000] {standard_task_runner.py:57} INFO - Started process 880 to run task
[2023-12-11T21:31:15.197+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_hook_overview', 'upload_to_snowflake', 'manual__2023-12-11T21:31:10.670571+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/load_into_snowflake.py', '--cfg-path', '/tmp/tmpgi_36pb7']
[2023-12-11T21:31:15.200+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask upload_to_snowflake
[2023-12-11T21:31:15.223+0000] {task_command.py:416} INFO - Running <TaskInstance: s3_hook_overview.upload_to_snowflake manual__2023-12-11T21:31:10.670571+00:00 [running]> on host 7e4ff88a419b
[2023-12-11T21:31:15.261+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_hook_overview' AIRFLOW_CTX_TASK_ID='upload_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T21:31:10.670571+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-11T21:31:10.670571+00:00'
[2023-12-11T21:31:15.273+0000] {copy_into_snowflake.py:139} INFO - Executing COPY command...
[2023-12-11T21:31:15.276+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-12-11T21:31:15.276+0000] {connection.py:334} INFO - Snowflake Connector for Python Version: 3.3.1, Python Version: 3.8.18, Platform: Linux-6.5.11-linuxkit-aarch64-with-glibc2.17
[2023-12-11T21:31:15.277+0000] {connection.py:1103} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-12-11T21:31:15.277+0000] {connection.py:1121} INFO - Setting use_openssl_only mode to False
[2023-12-11T21:31:15.845+0000] {cursor.py:833} INFO - query: [ALTER SESSION SET autocommit=True]
[2023-12-11T21:31:15.964+0000] {cursor.py:846} INFO - query execution done
[2023-12-11T21:31:15.965+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2023-12-11T21:31:15.965+0000] {sql.py:418} INFO - Running statement: COPY INTO my_schema.organizations
             FROM  @my_s3_stage/
        
        PATTERN='.*[.]csv'
        FILE_FORMAT=my_csv_format
        on_error=continue, parameters: None
[2023-12-11T21:31:15.966+0000] {cursor.py:833} INFO - query: [COPY INTO my_schema.organizations FROM  @my_s3_stage/  PATTERN='.*[.]csv' FILE_F...]
[2023-12-11T21:31:18.333+0000] {cursor.py:846} INFO - query execution done
[2023-12-11T21:31:18.336+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2023-12-11T21:31:18.336+0000] {sql.py:427} INFO - Rows affected: 1
[2023-12-11T21:31:18.337+0000] {snowflake.py:400} INFO - Rows affected: 1
[2023-12-11T21:31:18.338+0000] {snowflake.py:401} INFO - Snowflake query id: 01b0eccb-3200-f4fe-0000-000744422281
[2023-12-11T21:31:18.339+0000] {connection.py:677} INFO - closed
[2023-12-11T21:31:18.407+0000] {connection.py:683} INFO - No async queries seem to be running, deleting session
[2023-12-11T21:31:18.474+0000] {copy_into_snowflake.py:141} INFO - COPY command completed
[2023-12-11T21:31:18.475+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-11T21:31:18.491+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_hook_overview, task_id=upload_to_snowflake, execution_date=20231211T213110, start_date=20231211T213115, end_date=20231211T213118
[2023-12-11T21:31:18.513+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-11T21:31:18.528+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
